# Generated by Django 4.1.6 on 2023-02-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0003_film_imdb_rating_film_opis_film_plakat_film_premiera'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_genre',
            field=models.CharField(default='inne', max_length=64),
            preserve_default=False,
        ),
    ]
